### PR TITLE
Add publiccode.yml file

### PR DESCRIPTION
**Pull request by libremente**
La presente PR aggiunge il file `publiccode.yml` aderente alle ultime specifiche `core-0.2;it-0.2` illustrate sul portale [Docs Italia](https://docs.italia.it/italia/developers-italia/publiccodeyml/it/master/index.html).

Al momento alcune informazioni devono essere riviste e, per questo motivo, la PR è in modalità `Work-In-Progress`.
Nello specifico, mi servirebbero ulteriori informazioni riguardanti:
- [x] `repoOwner` -> in questo caso direi che è `Truelite srl`
- [x] Lista delle PA che attualmente utilizzano l'applicativo (da aggiungere alla chiave`usedBy`).
- [x] Aggiungere degli `screenshot` dell'applicativo (da inserire nel repository, ad esempio nella folder `screenshot` nella root).

Ovviamente rimango a disposizione per apportare qualsiasi correzione e/o integrazione necessaria al file.

Grazie molte per la disponibilità! @valholl @spanezz

### CODE REVIEW

**Comment by spanezz** [comment]
Thank you for the first draft of a `publiccode.yml` file!

Here are my comments on it, let me know which of them make sense:

Among `outputTypes`, one could add:
* `application/json` ([`a38tool json`](https://github.com/Truelite/python-a38/blob/master/a38tool.md#convert-a-fattura-to-json))
* python code ([`a38tool python`](https://github.com/Truelite/python-a38/blob/master/a38tool.md#generate-python-code)) (I don't know what mime type to use for python)
* `a38tool update_capath` can also generate a directory of CA certificates to use for verifying digital signatures, so in theory it also generates `application/x-x509-ca-cert`, if I got the mime type right?

I would like a Truelite group address to be the main contact point, and we need to work that out with Truelite. Similar for `mainCopyrightOwner`.

For localisation, the only significant strings are error messages and validation messages. They are currently in English, although they refer to Fattura Elettronica field names that are (sadly) in Italian, and the result is a strange hodge podge. It would be easy to mark those strings for translation, although I have little experience myself with distributing localised strings for libraries.

With regards to platforms, currently `linux` is listed, but the library can work in any OS that can run Python.

**Comment by libremente** [comment]
> Thank you for the first draft of a `publiccode.yml` file!
> 
> Here are my comments on it, let me know which of them make sense:
> 
> Among `outputTypes`, one could add:
> 
>     * `application/json` ([`a38tool json`](https://github.com/Truelite/python-a38/blob/master/a38tool.md#convert-a-fattura-to-json))
> 
>     * python code ([`a38tool python`](https://github.com/Truelite/python-a38/blob/master/a38tool.md#generate-python-code)) (I don't know what mime type to use for python)
> 
>     * `a38tool update_capath` can also generate a directory of CA certificates to use for verifying digital signatures, so in theory it also generates `application/x-x509-ca-cert`, if I got the mime type right?

Makes sense to me.

> 
> I would like a Truelite group address to be the main contact point, and we need to work that out with Truelite. Similar for `mainCopyrightOwner`.

Ok, can we keep the info currently in place and change them when you will have the new ones?

> For localisation, the only significant strings are error messages and validation messages. They are currently in English, although they refer to Fattura Elettronica field names that are (sadly) in Italian, and the result is a strange hodge podge. It would be easy to mark those strings for translation, although I have little experience myself with distributing localised strings for libraries.

Ok, let's put `en` then while you figure out how to proceed with the i18n process.

> With regards to platforms, currently `linux` is listed, but the library can work in any OS that can run Python.

Ok. 
Great, I'm uploading the file and I'll push ASAP. Keep in mind that the `publiccode.yml` is a "living" file so, since it lives in your repo, you can change it as you wish in the future.
Thanks a lot @spanezz for the prompt reply! :muscle:

**Comment by spanezz** [comment]
Ok, after talking about it internally, maintenance should become:
```
maintenance:
   type: internal
   contacts: 
    - name: Truelite srl
      email: a38@truelite.it 
```
and after this, I'm all for merging the pull request

**Comment by libremente** [comment]
Ok, should be ready now! Marking the PR as ready for review, thanks a lot @spanezz!

**Comment by spanezz** [comment]
Merged, thanks a lot for your help!

**Pull request merged**
